version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    command: celery -A mailing worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.dev.env
    # environment:
    #   - POSTGRES_DB=django_postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password
    depends_on:
      - django
      - redis
      - pgdb

  celery-beat:
    build: .
    command: celery -A mailing beat -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.dev.env
    # environment:
    #   - POSTGRES_DB=django_postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password
    depends_on:
      - django
      - redis
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - ./.dev.env
    # environment:
    #   - POSTGRES_DB=django_postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
