# Generated by Django 4.0.4 on 2022-05-25 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='api.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
