# Generated by Django 4.0.4 on 2022-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mailing_clients_alter_message_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='api.client'),
        ),
    ]
