# Generated by Django 4.0.4 on 2022-05-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mailing_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.mailing'),
        ),
    ]
