# Generated by Django 4.0.4 on 2022-05-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_parent_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing_id',
        ),
    ]
