# Generated by Django 3.2.13 on 2022-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220525_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
