# Generated by Django 3.2.13 on 2022-05-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mailing_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='fitler_tag',
            new_name='filter_tag',
        ),
    ]
