# Generated by Django 3.2.13 on 2022-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_fitler_tag_mailing_filter_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_scan', models.IntegerField()),
                ('project_status', models.BooleanField()),
            ],
        ),
    ]
