# Generated by Django 3.2.13 on 2022-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
