# Generated by Django 3.2.13 on 2022-06-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
